"""add query runs table

Revision ID: 0cec13e06a67
Revises: c158bd4a2558
Create Date: 2026-06-28 15:36:54.207650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cec13e06a67'
down_revision: Union[str, Sequence[str], None] = 'c158bd4a2558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('storage_backend', sa.String(length=128), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_runs_created_at', 'query_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_runs_dataset_id'), 'query_runs', ['dataset_id'], unique=False)
    op.create_index('ix_query_runs_status', 'query_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_query_runs_status', table_name='query_runs')
    op.drop_index(op.f('ix_query_runs_dataset_id'), table_name='query_runs')
    op.drop_index('ix_query_runs_created_at', table_name='query_runs')
    op.drop_table('query_runs')
    # ### end Alembic commands ###
